baseURL = 'https://williamcardenas.com/'
languageCode = 'en-us'
title = 'William CÃ¡rdenas'
theme = "paper" 


[params]
  name = ''
  bio = '...'
  avatar = 'https://williamcardenas.com/images/avatar.png'
  twitter = 'WilliamCar96'
  github = 'cardenaz'









[caches]
  [caches.images]
    dir = ':cacheDir/images'