baseURL = 'https://williamcardenas.com/'
languageCode = 'en-us'
title = 'William CÃ¡rdenas'
theme = "paper" 



[params]
  name = ''
  bio = '...'
  avatar = 'https://williamcardenas.com/images/avatar.png'





[caches]
  [caches.images]
    dir = ':cacheDir/images'