baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'William CÃ¡rdenas'
theme = "paper" 


[params]
  customCSS = ["css/custom.css"]


[caches]
  [caches.images]
    dir = ':cacheDir/images'